Add docker
luckysmo/shareit pull request #6
Opened 2022-10-28 20:17 UTC by luckysmo

2022-10-30 10:32 UTC, krylov-sergey-sergeevich requested changes
Привет, в целом очень неплохо, есть несколько замечаний/вопросов давай их проработаем и будем зачет ставить

2022-10-30 10:32 UTC, krylov-sergey-sergeevich commented on server/Dockerfile
> +COPY target/*.jar app.jar
Тоже тут можно улучшить

2022-10-30 10:32 UTC, krylov-sergey-sergeevich commented on server/src/main/java/ru/practicum/shareit/item/ItemController.java
> -                                              @PositiveOrZero Integer from,
А почему убрано?

2022-10-30 10:32 UTC, krylov-sergey-sergeevich commented on server/src/main/java/ru/practicum/shareit/item/ItemService.java
> +        Item item = itemRepository.findById(itemId).orElseThrow(() -> new ValidationException("Item not found!!!"));
Тут как будто бы NotFoundException подходило лучше + еще в идеале в исключение надо добавлять параметры по которым мы не нашли элемент

2022-10-30 10:32 UTC, krylov-sergey-sergeevich commented on server/src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +    @Transactional
Добавлено над методом точечно чтобы readonly перекрыть?

2022-10-30 20:44 UTC, luckysmo commented on server/src/main/java/ru/practicum/shareit/item/ItemController.java
> -                                              @PositiveOrZero Integer from,
как я понял ТЗ, из server убрать всю валидацию,и перенести ее в gateway

2022-10-30 20:46 UTC, luckysmo commented on server/src/main/java/ru/practicum/shareit/item/ItemService.java
> +        Item item = itemRepository.findById(itemId).orElseThrow(() -> new ValidationException("Item not found!!!"));
раньше так и было, в новых тестах постмана валился тест, у меня NotFoundException возвращает 404, а теперь требуется 400. Поэтому поменял.

2022-10-30 20:47 UTC, luckysmo commented on server/src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +    @Transactional
именно так)

2022-10-31 11:30 UTC, krylov-sergey-sergeevich approved these changes
Все хорошо - зачет!

2022-11-01 15:55 UTC, merged